import Link from 'next/link';
import type { ReactNode } from 'react';

export function Panel({ children, className = '', as: As = 'section' }: { children: ReactNode; className?: string; as?: 'section' | 'div' | 'article' }) {
  return <As className={`panel p-5 ${className}`}>{children}</As>;
}

export function SectionTitle({ children, hint }: { children: ReactNode; hint?: ReactNode }) {
  return (
    <div className="mb-3 flex items-baseline justify-between gap-4">
      <h2 className="font-display text-[15px] tracking-tight text-ink">{children}</h2>
      {hint ? <div className="text-xs text-ink-dim">{hint}</div> : null}
    </div>
  );
}

export function Money({ value, sub, accent = false }: { value: ReactNode; sub?: ReactNode; accent?: boolean }) {
  return (
    <div className="leading-tight">
      <div className={`money text-[15px] ${accent ? 'text-mint' : ''}`}>{value}</div>
      {sub ? <div className="text-[11px] text-ink-faint">{sub}</div> : null}
    </div>
  );
}

const TONES = {
  ok: 'border-mint/30 bg-mint/10 text-mint',
  warn: 'border-amber/30 bg-amber/10 text-amber',
  bad: 'border-rose/40 bg-rose/10 text-rose',
  neutral: 'border-hair bg-slate-900 text-ink-dim',
} as const;

export function Badge({ children, tone = 'neutral', title }: { children: ReactNode; tone?: keyof typeof TONES; title?: string }) {
  return (
    <span title={title} className={`inline-flex items-center gap-1.5 rounded-full border px-2 py-[3px] text-[11px] font-medium ${TONES[tone]}`}>
      {children}
    </span>
  );
}

/**
 * Every simulated number in this build carries its own label. The rule is not
 * decoration: an operator or a customer must never be able to mistake a sandbox
 * figure for a bank balance, so the tag travels with the value instead of sitting
 * once in a footer.
 */
export function SimulatedTag({ text = 'simulated', title }: { text?: string; title?: string }) {
  return (
    <span
      title={title ?? 'Generated by this sandbox. Not real money, a real chain, or a live partner response.'}
      className="ml-1.5 inline-flex items-center gap-1 rounded border border-amber/25 bg-amber/10 px-1 py-[1px] text-[9px] uppercase tracking-[0.12em] text-amber-dim align-middle"
    >
      {text}
    </span>
  );
}

export function Dot({ tone = 'ok', pulse = false }: { tone?: 'ok' | 'warn' | 'bad' | 'idle'; pulse?: boolean }) {
  const color = tone === 'ok' ? 'bg-mint' : tone === 'warn' ? 'bg-amber' : tone === 'bad' ? 'bg-rose' : 'bg-ink-faint';
  return <span className={`inline-block h-1.5 w-1.5 rounded-full ${color} ${pulse ? 'animate-pulseDot' : ''}`} />;
}

export function ErrorNote({ error, onRetry }: { error: unknown; onRetry?: () => void }) {
  if (!error) return null;
  const message = error instanceof Error ? error.message : String(error);
  return (
    <div role="alert" className="rounded-lg border border-rose-dim/40 bg-rose/8 px-3.5 py-3 text-sm text-rose">
      <div className="font-medium">Could not continue</div>
      <div className="mt-0.5 text-[13px] leading-relaxed text-rose/90">{message}</div>
      {onRetry ? (
        <button type="button" onClick={onRetry} className="mt-2 text-[12px] underline decoration-dotted hover:text-ink">
          Try again
        </button>
      ) : null}
    </div>
  );
}

export function Loading({ label = 'Loading' }: { label?: string }) {
  return (
    <div className="flex items-center gap-2 text-sm text-ink-dim">
      <span className="h-1.5 w-1.5 animate-pulseDot rounded-full bg-mint" />
      {label}…
    </div>
  );
}

export function KV({ k, v, mono = false }: { k: ReactNode; v: ReactNode; mono?: boolean }) {
  return (
    <div className="flex items-baseline justify-between gap-4 border-b border-hair/60 py-2 last:border-0">
      <dt className="text-[12px] text-ink-dim">{k}</dt>
      <dd className={`text-right text-[13px] text-ink ${mono ? 'money' : ''}`}>{v}</dd>
    </div>
  );
}

export function Brand({ href = '/', size = 'md' }: { href?: string; size?: 'sm' | 'md' }) {
  return (
    <Link href={href} className="group inline-flex items-center gap-2.5">
      <span className="relative grid h-7 w-7 place-items-center">
        {/* The mark: a ledger line through an aperture — money passing a checkpoint. */}
        <span className="absolute inset-0 rounded-[9px] border border-mint/40 bg-mint/8 transition group-hover:border-mint/70" />
        <span className="relative h-[2px] w-3.5 rounded-full bg-mint" />
        <span className="absolute h-[13px] w-[13px] rounded-full border border-ink/25" />
      </span>
      <span className={`font-display tracking-[-0.02em] text-ink ${size === 'md' ? 'text-[19px]' : 'text-[15px]'}`}>
        AuraPay
      </span>
    </Link>
  );
}
